#!/bin/bash
# Export no-split proxies of official maps from DRA.
scripts-1time/export_official_proxy.sh --state AL --plantype congress --name AL_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state AL --plantype lower --name AL_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state AL --plantype upper --name AL_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state AZ --plantype congress --name AZ_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state AZ --plantype upper --name AZ_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state AR --plantype congress --name AR_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state AR --plantype lower --name AR_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state AR --plantype upper --name AR_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state CA --plantype congress --name CA_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state CA --plantype lower --name CA_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state CA --plantype upper --name CA_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state CO --plantype congress --name CO_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state CO --plantype lower --name CO_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state CO --plantype upper --name CO_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state CT --plantype congress --name CT_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state CT --plantype lower --name CT_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state CT --plantype upper --name CT_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state FL --plantype congress --name FL_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state FL --plantype lower --name FL_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state FL --plantype upper --name FL_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state GA --plantype congress --name GA_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state GA --plantype lower --name GA_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state GA --plantype upper --name GA_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state ID --plantype congress --name ID_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state ID --plantype upper --name ID_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state IL --plantype congress --name IL_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state IL --plantype lower --name IL_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state IL --plantype upper --name IL_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state IN --plantype congress --name IN_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state IN --plantype lower --name IN_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state IN --plantype upper --name IN_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state IA --plantype congress --name IA_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state IA --plantype lower --name IA_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state IA --plantype upper --name IA_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state KS --plantype congress --name KS_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state KS --plantype lower --name KS_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state KS --plantype upper --name KS_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state KY --plantype congress --name KY_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state KY --plantype lower --name KY_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state KY --plantype upper --name KY_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state LA --plantype congress --name LA_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state LA --plantype lower --name LA_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state LA --plantype upper --name LA_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MA --plantype congress --name MA_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MA --plantype lower --name MA_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MA --plantype upper --name MA_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MD --plantype congress --name MD_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MD --plantype lower --name MD_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MD --plantype upper --name MD_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MI --plantype congress --name MI_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MI --plantype lower --name MI_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MI --plantype upper --name MI_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MN --plantype congress --name MN_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MN --plantype lower --name MN_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MN --plantype upper --name MN_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MS --plantype congress --name MS_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MS --plantype lower --name MS_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MS --plantype upper --name MS_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MO --plantype congress --name MO_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MO --plantype lower --name MO_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MO --plantype upper --name MO_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MT --plantype congress --name MT_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MT --plantype lower --name MT_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state MT --plantype upper --name MT_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NE --plantype congress --name NE_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NE --plantype upper --name NE_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NH --plantype congress --name NH_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NH --plantype lower --name NH_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NH --plantype upper --name NH_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NV --plantype congress --name NV_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NV --plantype lower --name NV_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NV --plantype upper --name NV_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NJ --plantype congress --name NJ_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NJ --plantype upper --name NJ_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NM --plantype congress --name NM_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NM --plantype lower --name NM_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NM --plantype upper --name NM_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NY --plantype congress --name NY_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NY --plantype lower --name NY_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NY --plantype upper --name NY_2022_Upper_Official_Proxy.csv
# scripts-1time/export_official_proxy.sh --state NC --plantype congress --name NC_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NC --plantype lower --name NC_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state NC --plantype upper --name NC_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state OH --plantype congress --name OH_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state OH --plantype lower --name OH_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state OH --plantype upper --name OH_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state OK --plantype congress --name OK_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state OK --plantype lower --name OK_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state OK --plantype upper --name OK_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state OR --plantype congress --name OR_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state OR --plantype lower --name OR_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state OR --plantype upper --name OR_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state PA --plantype congress --name PA_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state PA --plantype lower --name PA_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state PA --plantype upper --name PA_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state RI --plantype congress --name RI_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state RI --plantype lower --name RI_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state RI --plantype upper --name RI_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state SC --plantype congress --name SC_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state SC --plantype upper --name SC_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state SC --plantype lower --name SC_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state TN --plantype congress --name TN_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state TN --plantype lower --name TN_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state TN --plantype upper --name TN_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state TX --plantype congress --name TX_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state TX --plantype lower --name TX_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state TX --plantype upper --name TX_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state UT --plantype congress --name UT_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state UT --plantype lower --name UT_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state UT --plantype upper --name UT_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state VA --plantype congress --name VA_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state VA --plantype lower --name VA_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state VA --plantype upper --name VA_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state WA --plantype congress --name WA_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state WA --plantype upper --name WA_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state WI --plantype congress --name WI_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state WI --plantype lower --name WI_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state WI --plantype upper --name WI_2022_Upper_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state WV --plantype congress --name WV_2022_Congress_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state WV --plantype lower --name WV_2022_Lower_Official_Proxy.csv
scripts-1time/export_official_proxy.sh --state WV --plantype upper --name WV_2022_Upper_Official_Proxy.csv
