#!/bin/bash
# Make focus ratings tables for the copies of official maps in DRA.
scripts-1time/make_focus_ratings_table.py --state AL --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state AL --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state AZ --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state AR --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state AR --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state CA --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state CA --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state CO --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state CO --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state CT --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state CT --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state FL --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state FL --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state GA --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state GA --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state ID --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state IN --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state IN --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state IA --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state IA --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state KS --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state KS --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state KY --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state KY --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state LA --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state LA --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MA --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MA --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MI --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MI --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MN --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MN --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MS --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MS --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MO --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MO --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MT --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state MT --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state NE --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state NH --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state NH --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state NV --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state NV --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state NJ --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state NM --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state NM --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state NY --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state NY --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state OH --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state OH --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state OK --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state OK --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state OR --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state OR --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state RI --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state RI --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state TN --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state TN --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state UT --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state UT --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state VA --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state VA --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state WA --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state WI --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state WI --plantype Upper --no-debug -v
scripts-1time/make_focus_ratings_table.py --state WV --plantype Lower --no-debug -v
scripts-1time/make_focus_ratings_table.py --state WV --plantype Upper --no-debug -v
