#!/bin/bash
# Make focus ratings tables for the copies of official maps in DRA.
scripts-1time/make_focus_ratings_table.py --state AL --plantype Congress
scripts-1time/make_focus_ratings_table.py --state AL --plantype Lower
scripts-1time/make_focus_ratings_table.py --state AL --plantype Upper
scripts-1time/make_focus_ratings_table.py --state AZ --plantype Congress
scripts-1time/make_focus_ratings_table.py --state AZ --plantype Upper
scripts-1time/make_focus_ratings_table.py --state AR --plantype Congress
scripts-1time/make_focus_ratings_table.py --state AR --plantype Lower
scripts-1time/make_focus_ratings_table.py --state AR --plantype Upper
scripts-1time/make_focus_ratings_table.py --state CA --plantype Congress
scripts-1time/make_focus_ratings_table.py --state CA --plantype Lower
scripts-1time/make_focus_ratings_table.py --state CA --plantype Upper
scripts-1time/make_focus_ratings_table.py --state CO --plantype Congress
scripts-1time/make_focus_ratings_table.py --state CO --plantype Lower
scripts-1time/make_focus_ratings_table.py --state CO --plantype Upper
scripts-1time/make_focus_ratings_table.py --state CT --plantype Congress
scripts-1time/make_focus_ratings_table.py --state CT --plantype Lower
scripts-1time/make_focus_ratings_table.py --state CT --plantype Upper
scripts-1time/make_focus_ratings_table.py --state FL --plantype Congress
scripts-1time/make_focus_ratings_table.py --state FL --plantype Lower
scripts-1time/make_focus_ratings_table.py --state FL --plantype Upper
scripts-1time/make_focus_ratings_table.py --state GA --plantype Congress
scripts-1time/make_focus_ratings_table.py --state GA --plantype Lower
scripts-1time/make_focus_ratings_table.py --state GA --plantype Upper
scripts-1time/make_focus_ratings_table.py --state ID --plantype Congress
scripts-1time/make_focus_ratings_table.py --state ID --plantype Upper
scripts-1time/make_focus_ratings_table.py --state IN --plantype Congress
scripts-1time/make_focus_ratings_table.py --state IN --plantype Lower
scripts-1time/make_focus_ratings_table.py --state IN --plantype Upper
scripts-1time/make_focus_ratings_table.py --state IA --plantype Congress
scripts-1time/make_focus_ratings_table.py --state IA --plantype Lower
scripts-1time/make_focus_ratings_table.py --state IA --plantype Upper
scripts-1time/make_focus_ratings_table.py --state KS --plantype Congress
scripts-1time/make_focus_ratings_table.py --state KS --plantype Lower
scripts-1time/make_focus_ratings_table.py --state KS --plantype Upper
scripts-1time/make_focus_ratings_table.py --state KY --plantype Congress
scripts-1time/make_focus_ratings_table.py --state KY --plantype Lower
scripts-1time/make_focus_ratings_table.py --state KY --plantype Upper
scripts-1time/make_focus_ratings_table.py --state LA --plantype Congress
scripts-1time/make_focus_ratings_table.py --state LA --plantype Lower
scripts-1time/make_focus_ratings_table.py --state LA --plantype Upper
scripts-1time/make_focus_ratings_table.py --state MA --plantype Congress
scripts-1time/make_focus_ratings_table.py --state MA --plantype Lower
scripts-1time/make_focus_ratings_table.py --state MA --plantype Upper
scripts-1time/make_focus_ratings_table.py --state MI --plantype Congress
scripts-1time/make_focus_ratings_table.py --state MI --plantype Lower
scripts-1time/make_focus_ratings_table.py --state MI --plantype Upper
scripts-1time/make_focus_ratings_table.py --state MN --plantype Congress
scripts-1time/make_focus_ratings_table.py --state MN --plantype Lower
scripts-1time/make_focus_ratings_table.py --state MN --plantype Upper
scripts-1time/make_focus_ratings_table.py --state MS --plantype Congress
scripts-1time/make_focus_ratings_table.py --state MS --plantype Lower
scripts-1time/make_focus_ratings_table.py --state MS --plantype Upper
scripts-1time/make_focus_ratings_table.py --state MO --plantype Congress
scripts-1time/make_focus_ratings_table.py --state MO --plantype Lower
scripts-1time/make_focus_ratings_table.py --state MO --plantype Upper
scripts-1time/make_focus_ratings_table.py --state MT --plantype Congress
scripts-1time/make_focus_ratings_table.py --state MT --plantype Lower
scripts-1time/make_focus_ratings_table.py --state MT --plantype Upper
scripts-1time/make_focus_ratings_table.py --state NE --plantype Congress
scripts-1time/make_focus_ratings_table.py --state NE --plantype Upper
scripts-1time/make_focus_ratings_table.py --state NH --plantype Congress
scripts-1time/make_focus_ratings_table.py --state NH --plantype Lower
scripts-1time/make_focus_ratings_table.py --state NH --plantype Upper
scripts-1time/make_focus_ratings_table.py --state NV --plantype Congress
scripts-1time/make_focus_ratings_table.py --state NV --plantype Lower
scripts-1time/make_focus_ratings_table.py --state NV --plantype Upper
scripts-1time/make_focus_ratings_table.py --state NJ --plantype Congress
scripts-1time/make_focus_ratings_table.py --state NJ --plantype Upper
scripts-1time/make_focus_ratings_table.py --state NM --plantype Congress
scripts-1time/make_focus_ratings_table.py --state NM --plantype Lower
scripts-1time/make_focus_ratings_table.py --state NM --plantype Upper
scripts-1time/make_focus_ratings_table.py --state NY --plantype Congress
scripts-1time/make_focus_ratings_table.py --state NY --plantype Lower
scripts-1time/make_focus_ratings_table.py --state NY --plantype Upper
scripts-1time/make_focus_ratings_table.py --state OH --plantype Congress
scripts-1time/make_focus_ratings_table.py --state OH --plantype Lower
scripts-1time/make_focus_ratings_table.py --state OH --plantype Upper
scripts-1time/make_focus_ratings_table.py --state OK --plantype Congress
scripts-1time/make_focus_ratings_table.py --state OK --plantype Lower
scripts-1time/make_focus_ratings_table.py --state OK --plantype Upper
scripts-1time/make_focus_ratings_table.py --state OR --plantype Congress
scripts-1time/make_focus_ratings_table.py --state OR --plantype Lower
scripts-1time/make_focus_ratings_table.py --state OR --plantype Upper
scripts-1time/make_focus_ratings_table.py --state RI --plantype Congress
scripts-1time/make_focus_ratings_table.py --state RI --plantype Lower
scripts-1time/make_focus_ratings_table.py --state RI --plantype Upper
scripts-1time/make_focus_ratings_table.py --state TN --plantype Congress
scripts-1time/make_focus_ratings_table.py --state TN --plantype Lower
scripts-1time/make_focus_ratings_table.py --state TN --plantype Upper
scripts-1time/make_focus_ratings_table.py --state UT --plantype Congress
scripts-1time/make_focus_ratings_table.py --state UT --plantype Lower
scripts-1time/make_focus_ratings_table.py --state UT --plantype Upper
scripts-1time/make_focus_ratings_table.py --state VA --plantype Congress
scripts-1time/make_focus_ratings_table.py --state VA --plantype Lower
scripts-1time/make_focus_ratings_table.py --state VA --plantype Upper
scripts-1time/make_focus_ratings_table.py --state WA --plantype Congress
scripts-1time/make_focus_ratings_table.py --state WA --plantype Upper
scripts-1time/make_focus_ratings_table.py --state WI --plantype Congress
scripts-1time/make_focus_ratings_table.py --state WI --plantype Lower
scripts-1time/make_focus_ratings_table.py --state WI --plantype Upper
scripts-1time/make_focus_ratings_table.py --state WV --plantype Congress
scripts-1time/make_focus_ratings_table.py --state WV --plantype Lower
scripts-1time/make_focus_ratings_table.py --state WV --plantype Upper
