#!/bin/bash
# Make notable ratings tables for the copies of notable maps in DRA.
scripts-1time/make_notable_ratings_table.py --state AL --plantype Upper
scripts-1time/make_notable_ratings_table.py --state AL --plantype Lower
scripts-1time/make_notable_ratings_table.py --state AK --plantype Upper
scripts-1time/make_notable_ratings_table.py --state AK --plantype Lower
scripts-1time/make_notable_ratings_table.py --state AZ --plantype Upper
scripts-1time/make_notable_ratings_table.py --state AR --plantype Upper
scripts-1time/make_notable_ratings_table.py --state AR --plantype Lower
scripts-1time/make_notable_ratings_table.py --state CA --plantype Upper
scripts-1time/make_notable_ratings_table.py --state CA --plantype Lower
scripts-1time/make_notable_ratings_table.py --state CO --plantype Upper
scripts-1time/make_notable_ratings_table.py --state CO --plantype Lower
scripts-1time/make_notable_ratings_table.py --state CT --plantype Upper
scripts-1time/make_notable_ratings_table.py --state CT --plantype Lower
scripts-1time/make_notable_ratings_table.py --state DE --plantype Upper
scripts-1time/make_notable_ratings_table.py --state DE --plantype Lower
scripts-1time/make_notable_ratings_table.py --state FL --plantype Upper
scripts-1time/make_notable_ratings_table.py --state FL --plantype Lower
scripts-1time/make_notable_ratings_table.py --state GA --plantype Upper
scripts-1time/make_notable_ratings_table.py --state GA --plantype Lower
scripts-1time/make_notable_ratings_table.py --state HI --plantype Upper
scripts-1time/make_notable_ratings_table.py --state HI --plantype Lower
scripts-1time/make_notable_ratings_table.py --state ID --plantype Upper
scripts-1time/make_notable_ratings_table.py --state IL --plantype Upper
scripts-1time/make_notable_ratings_table.py --state IL --plantype Lower
scripts-1time/make_notable_ratings_table.py --state IN --plantype Upper
scripts-1time/make_notable_ratings_table.py --state IN --plantype Lower
scripts-1time/make_notable_ratings_table.py --state IA --plantype Upper
scripts-1time/make_notable_ratings_table.py --state IA --plantype Lower
scripts-1time/make_notable_ratings_table.py --state KS --plantype Upper
scripts-1time/make_notable_ratings_table.py --state KS --plantype Lower
scripts-1time/make_notable_ratings_table.py --state KY --plantype Upper
scripts-1time/make_notable_ratings_table.py --state KY --plantype Lower
scripts-1time/make_notable_ratings_table.py --state LA --plantype Upper
scripts-1time/make_notable_ratings_table.py --state LA --plantype Lower
scripts-1time/make_notable_ratings_table.py --state ME --plantype Upper
scripts-1time/make_notable_ratings_table.py --state ME --plantype Lower
scripts-1time/make_notable_ratings_table.py --state MD --plantype Upper
scripts-1time/make_notable_ratings_table.py --state MD --plantype Lower
scripts-1time/make_notable_ratings_table.py --state MA --plantype Upper
scripts-1time/make_notable_ratings_table.py --state MA --plantype Lower
scripts-1time/make_notable_ratings_table.py --state MI --plantype Upper
scripts-1time/make_notable_ratings_table.py --state MI --plantype Lower
scripts-1time/make_notable_ratings_table.py --state MN --plantype Upper
scripts-1time/make_notable_ratings_table.py --state MN --plantype Lower
scripts-1time/make_notable_ratings_table.py --state MS --plantype Upper
scripts-1time/make_notable_ratings_table.py --state MS --plantype Lower
scripts-1time/make_notable_ratings_table.py --state MO --plantype Upper
scripts-1time/make_notable_ratings_table.py --state MO --plantype Lower
scripts-1time/make_notable_ratings_table.py --state MT --plantype Upper
scripts-1time/make_notable_ratings_table.py --state MT --plantype Lower
scripts-1time/make_notable_ratings_table.py --state NE --plantype Upper
scripts-1time/make_notable_ratings_table.py --state NV --plantype Upper
scripts-1time/make_notable_ratings_table.py --state NV --plantype Lower
scripts-1time/make_notable_ratings_table.py --state NH --plantype Upper
scripts-1time/make_notable_ratings_table.py --state NH --plantype Lower
scripts-1time/make_notable_ratings_table.py --state NJ --plantype Upper
scripts-1time/make_notable_ratings_table.py --state NM --plantype Upper
scripts-1time/make_notable_ratings_table.py --state NM --plantype Lower
scripts-1time/make_notable_ratings_table.py --state NY --plantype Upper
scripts-1time/make_notable_ratings_table.py --state NY --plantype Lower
scripts-1time/make_notable_ratings_table.py --state NC --plantype Upper
scripts-1time/make_notable_ratings_table.py --state NC --plantype Lower
scripts-1time/make_notable_ratings_table.py --state ND --plantype Upper
scripts-1time/make_notable_ratings_table.py --state ND --plantype Lower
scripts-1time/make_notable_ratings_table.py --state OH --plantype Upper
scripts-1time/make_notable_ratings_table.py --state OH --plantype Lower
scripts-1time/make_notable_ratings_table.py --state OK --plantype Upper
scripts-1time/make_notable_ratings_table.py --state OK --plantype Lower
scripts-1time/make_notable_ratings_table.py --state OR --plantype Upper
scripts-1time/make_notable_ratings_table.py --state OR --plantype Lower
scripts-1time/make_notable_ratings_table.py --state PA --plantype Upper
scripts-1time/make_notable_ratings_table.py --state PA --plantype Lower
scripts-1time/make_notable_ratings_table.py --state RI --plantype Upper
scripts-1time/make_notable_ratings_table.py --state RI --plantype Lower
scripts-1time/make_notable_ratings_table.py --state SC --plantype Upper
scripts-1time/make_notable_ratings_table.py --state SC --plantype Lower
scripts-1time/make_notable_ratings_table.py --state SD --plantype Upper
scripts-1time/make_notable_ratings_table.py --state SD --plantype Lower
scripts-1time/make_notable_ratings_table.py --state TN --plantype Upper
scripts-1time/make_notable_ratings_table.py --state TN --plantype Lower
scripts-1time/make_notable_ratings_table.py --state TX --plantype Upper
scripts-1time/make_notable_ratings_table.py --state TX --plantype Lower
scripts-1time/make_notable_ratings_table.py --state UT --plantype Upper
scripts-1time/make_notable_ratings_table.py --state UT --plantype Lower
scripts-1time/make_notable_ratings_table.py --state VT --plantype Upper
scripts-1time/make_notable_ratings_table.py --state VT --plantype Lower
scripts-1time/make_notable_ratings_table.py --state VA --plantype Upper
scripts-1time/make_notable_ratings_table.py --state VA --plantype Lower
scripts-1time/make_notable_ratings_table.py --state WA --plantype Upper
scripts-1time/make_notable_ratings_table.py --state WV --plantype Upper
scripts-1time/make_notable_ratings_table.py --state WV --plantype Lower
scripts-1time/make_notable_ratings_table.py --state WI --plantype Upper
scripts-1time/make_notable_ratings_table.py --state WI --plantype Lower
scripts-1time/make_notable_ratings_table.py --state WY --plantype Upper
scripts-1time/make_notable_ratings_table.py --state WY --plantype Lower
