#!/bin/bash
# Pull ratings for copies of notable maps in DRA.
scripts-1time/pull_map_ratings.sh AL 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AL 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AL 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AL 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AL 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AL 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AL 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AL 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AL 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AL 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AK 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AK 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AK 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AK 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AK 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AK 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AK 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AK 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AK 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AK 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AZ 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AZ 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AZ 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AZ 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AZ 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AR 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AR 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AR 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AR 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AR 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AR 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AR 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AR 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AR 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh AR 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CA 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CA 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CA 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CA 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CA 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CA 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CA 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CA 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CA 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CA 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CO 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CO 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CO 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CO 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CO 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CO 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CO 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CO 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CO 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CO 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CT 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CT 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CT 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CT 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CT 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CT 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CT 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CT 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CT 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh CT 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh DE 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh DE 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh DE 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh DE 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh DE 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh DE 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh DE 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh DE 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh DE 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh DE 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh FL 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh FL 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh FL 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh FL 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh FL 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh FL 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh FL 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh FL 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh FL 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh FL 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh GA 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh GA 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh GA 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh GA 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh GA 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh GA 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh GA 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh GA 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh GA 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh GA 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh HI 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh HI 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh HI 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh HI 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh HI 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh HI 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh HI 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh HI 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh HI 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh HI 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ID 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ID 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ID 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ID 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ID 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IL 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IL 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IL 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IL 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IL 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IL 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IL 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IL 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IL 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IL 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IN 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IN 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IN 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IN 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IN 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IN 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IN 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IN 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IN 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IN 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IA 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IA 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IA 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IA 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IA 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IA 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IA 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IA 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IA 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh IA 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KS 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KS 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KS 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KS 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KS 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KS 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KS 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KS 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KS 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KS 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KY 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KY 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KY 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KY 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KY 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KY 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KY 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KY 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KY 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh KY 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh LA 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh LA 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh LA 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh LA 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh LA 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh LA 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh LA 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh LA 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh LA 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh LA 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ME 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ME 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ME 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ME 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ME 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ME 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ME 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ME 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ME 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ME 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MD 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MD 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MD 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MD 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MD 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MD 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MD 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MD 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MD 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MD 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MA 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MA 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MA 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MA 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MA 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MA 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MA 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MA 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MA 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MA 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MI 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MI 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MI 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MI 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MI 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MI 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MI 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MI 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MI 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MI 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MN 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MN 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MN 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MN 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MN 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MN 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MN 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MN 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MN 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MN 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MS 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MS 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MS 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MS 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MS 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MS 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MS 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MS 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MS 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MS 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MO 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MO 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MO 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MO 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MO 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MO 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MO 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MO 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MO 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MO 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MT 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MT 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MT 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MT 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MT 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MT 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MT 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MT 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MT 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh MT 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NE 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NE 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NE 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NE 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NE 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NV 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NV 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NV 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NV 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NV 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NV 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NV 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NV 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NV 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NV 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NH 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NH 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NH 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NH 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NH 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NH 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NH 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NH 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NH 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NH 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NJ 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NJ 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NJ 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NJ 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NJ 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NM 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NM 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NM 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NM 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NM 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NM 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NM 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NM 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NM 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NM 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NY 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NY 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NY 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NY 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NY 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NY 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NY 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NY 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NY 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NY 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NC 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NC 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NC 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NC 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NC 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NC 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NC 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NC 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NC 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh NC 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ND 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ND 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ND 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ND 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ND 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ND 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ND 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ND 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ND 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh ND 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OH 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OH 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OH 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OH 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OH 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OH 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OH 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OH 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OH 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OH 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OK 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OK 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OK 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OK 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OK 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OK 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OK 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OK 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OK 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OK 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OR 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OR 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OR 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OR 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OR 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OR 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OR 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OR 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OR 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh OR 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh PA 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh PA 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh PA 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh PA 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh PA 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh PA 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh PA 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh PA 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh PA 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh PA 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh RI 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh RI 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh RI 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh RI 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh RI 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh RI 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh RI 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh RI 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh RI 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh RI 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SC 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SC 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SC 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SC 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SC 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SC 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SC 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SC 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SC 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SC 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SD 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SD 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SD 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SD 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SD 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SD 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SD 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SD 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SD 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh SD 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TN 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TN 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TN 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TN 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TN 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TN 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TN 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TN 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TN 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TN 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TX 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TX 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TX 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TX 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TX 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TX 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TX 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TX 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TX 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh TX 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh UT 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh UT 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh UT 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh UT 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh UT 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh UT 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh UT 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh UT 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh UT 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh UT 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VT 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VT 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VT 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VT 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VT 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VT 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VT 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VT 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VT 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VT 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VA 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VA 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VA 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VA 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VA 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VA 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VA 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VA 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VA 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh VA 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WA 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WA 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WA 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WA 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WA 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WV 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WV 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WV 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WV 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WV 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WV 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WV 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WV 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WV 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WV 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WI 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WI 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WI 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WI 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WI 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WI 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WI 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WI 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WI 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WI 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WY 2022 Upper Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WY 2022 Upper Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WY 2022 Upper Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WY 2022 Upper Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WY 2022 Upper Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WY 2022 Lower Proportional xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WY 2022 Lower Competitive xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WY 2022 Lower Minority xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WY 2022 Lower Compact xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
scripts-1time/pull_map_ratings.sh WY 2022 Lower Splitting xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx intermediate
